config/routes.rb
Rails.application.routes.draw do


  devise_for :users

  resources :users, only: [:show]

  resources :topics do
    resources :bookmarks
  end

  resources :bookmarks, except: [:index] do
    resources :likes, only: [:index, :create, :destroy]
  end

  post :incoming, to: 'incoming#create'

  get 'users/show'
  
  get 'welcome/index'

  get 'welcome/about'

  get 'likes/index'

  root 'welcome#index'
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
  has_many :likes, dependent: :destroy
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :bookmark
  belongs_to :user
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :bookmarks, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :topics, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :likes, dependent: :destroy

  def liked(bookmark)
    likes.where(bookmark_id: bookmark.id).first
  end
  
  def liked_bookmarks
    likes.includes(bookmark: :topic).map(&:bookmark)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def show
    @bookmark = Bookmark.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.new
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.topic = @topic
    @bookmark.user = current_user

    if @bookmark.save
      flash[:notice] = "Bookmark Saved"
      redirect_to topic_path(@topic)
    else
      flash[:alert] = "Failed to save Bookmark"
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:id])
    authorize @bookmark

    if @bookmark.update(bookmark_params)
      flash[:notice] = "Bookmark Updated"
      redirect_to topic_path(@topic)
    else
      flash[:alert] = "Failed to update bookmark"
      render :edit
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    authorize @bookmark

    if @bookmark.destroy
      flash[:notice] = "Bookmark deleted"
      redirect_to topics_path(@topic)
    else
      flash[:alert] = "Failed to delete bookmark"
      render :show
    end
  end

  private
  def bookmark_params
    params.require(:bookmark).permit(:url)
  end
end

app/controllers/incoming_controller.rb
class IncomingController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create]
  skip_before_action :authenticate_user!

  def create

    # Find the user by using params[:sender]
    @user = User.find_by(email: params[:sender])
    # Find the topic by using params[:subject]
    @topic = Topic.find_or_create_by(title: params[:subject])
    # Assign the url to a variable after retreiving it from params["body-plain"]
    @bookmark.url = params["body-plain"]
    # Check if user is nil, if so, create and save a new user
    if user.nil?
     redirect_to new_user_path
    end
    # Check if the topic is nil, if so, create and save a new topic
    if topic.nil?
     redirect_to new_topic_path
    end
    # Now that you're sure you have a valid user and topic, build and save a new bookmark
    @bookmark = Bookmark.new
    @bookmark.topic = @topic
    @bookmark.user = current_user
    @bookmark.save!
    head 200
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @bookmark = Bookmark.find(params[:bookmark_id])
    @like = current_user.likes.build(bookmark: @bookmark)
    @bookmark.topic = @topic

    if @like.save
      flash[:notice] = "Bookmark Liked"
      redirect_to [@topic, @bookmark]
    else
      flash[:alert] = "Failed to Like Bookmark"
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:bookmark_id])
    @like = current_user.likes.find_by(bookmark: @bookmark)
    @bookmark.topic = @topic

    if @like.destroy
      flash[:notice] = "Bookmark Unliked"
      redirect_to [@topic, @bookmark]
    else
      flash[:alert] = "Failed to Unlike Bookmark"
      render :show
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user = current_user
    if @topic.save
      flash[:notice] = "Topic saved successfully"
      redirect_to topic_path(@topic)
    else
      flash[:alert] = "Failed to save topic"
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])

    if @topic.update(topic_params)
      flash[:notice] = "Topic Updated"
      redirect_to topic_path(@topic)
    else
      flash[:alert] = "Failed to update Topic"
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    if @topic.destroy
      flash[:notice] = "Topic Deleted"
      redirect_to topics_path
    else
      flash[:alert] = "Failed to delete topic"
      render :show
    end
  end

  private
  def topic_params
    params.require(:topic).permit(:title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user_bookmarks = current_user.bookmarks
    @liked_bookmarks = current_user.liked_bookmarks
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/incoming_helper.rb
module IncomingHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookmarks/_form.html.erb
<%= form_for [@topic, @bookmark] do |f| %>
  <div class="form-group">
    <%= f.label :url %><br />
    <%= f.text_field :url, class: 'form-control', placeholder: 'Enter your Bookmark URL here' %>
    <%= f.submit "Save" %>
  </div>
<% end %>

app/views/bookmarks/edit.html.erb
<h1 class="title">Edit Bookmark</h1>
<%= render partial: 'form', locals: { bookmark: @bookmark } %>

app/views/bookmarks/new.html.erb
<h1 class="title">Add a Bookmark</h1>
<%= render partial: 'form', locals: { bookmark: @bookmark.topic } %>

app/views/bookmarks/show.html.erb
<h1 class="title"><%= @bookmark.url %></h1><br />
  <%= render partial: 'likes/like', locals: { bookmark: @bookmark, like: @like } %>
  <% if policy(@bookmark).edit? %>
      <%= link_to "Edit Bookmark", edit_topic_bookmark_path(@bookmark.topic, @bookmark), class: 'btn btn-primary' %>
  <% end %>
  <% if policy(@bookmark).destroy? %>
    <%= link_to "Delete Bookmark", [@topic, @bookmark], method: :delete, class: 'btn btn-danger', data: { confirm: 'Delete this Bookmark?' } %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rockmarks</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script async src="//cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", welcome_index_path %></li>
      <li><%= link_to "My RockMarks", users_show_path %></li>
      <li><%= link_to "Topics", topics_path %></li>
      <li><%= link_to "About", welcome_about_path %></li>
      <div class="pull-right user-bar">
      <% if user_signed_in? %>
        <strong><%= link_to current_user.email, edit_user_registration_path,
        :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path,
        method: :delete, :class => 'navbar-link' %>
      <% else %>
        <%= link_to "Register", new_user_registration_path, :class => 'navbar-link' %> -
        <%= link_to "Log In", new_user_session_path, :class => 'navbar-link' %>
      <% end %>
      </div>
    </ul>
  <div class="flash">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash.now[:alert] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash.now[:alert] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>
  </div>
<%= yield %>
  </div>

</body>
</html>

app/views/likes/_like.html.erb
<% if policy(Like.new).create? %>
  <div>
    <% if like = current_user.liked(bookmark) %>
      <%= link_to [bookmark, like], class: 'btn btn-danger', method: :delete do %>
        <i class="glyphicon glyphicon-star-empty"> </i>&nbsp; Unlike
      <% end %>
    <% else %>
      <%= link_to [bookmark, Like.new], class: 'btn btn-primary', method: :post do %>
        <i class="glyphicon glyphicon-star"> </i>&nbsp; Like
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/likes/index.html.erb
<h1>Likes#index</h1>
<p>Find me in app/views/likes/index.html.erb</p>

app/views/topics/_form.html.erb
<%= form_for @topic do |f| %>
  <div class="form-group">
    <%= f.label :topic %><br />
    <%= f.text_field :title, class: 'form-control', placeholder: 'Topic Title' %><br />
    <%= f.submit "Save" %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h4> Edit Topic </h4>
  <%= render partial: 'form', locals: { topic: @topic } %>
</div>

app/views/topics/index.html.erb
<h1 class="title">RockiTopics</h1><br />
  <div class="row">
    <div class="col-md-4">
      <%= link_to "New Topic", new_topic_path, class: 'btn btn-primary' %>
    </div>
      <div class="col-md-8">
        <% @topics.each do |topic| %>
          <%= link_to topic.title, topic %>
        <% end %>
      </div>
  </div>

app/views/topics/new.html.erb
<h4> Create A Topic </h4>
  <%= render partial: 'form', locals: { topic: @topic } %>
</div>

app/views/topics/show.html.erb
<div class="container">
  <h1 class="title"> <%= @topic.title %> </h1><br />
      <%= link_to "Add a Bookmark", new_topic_bookmark_path(@topic, @bookmark), class: 'btn btn-success' %>
      <%= link_to "Edit Topic", edit_topic_path, class: 'btn btn-primary' %>
    <div class="pull-right">
      <%= link_to "Delete Topic", @topic,
      method: :delete, class: 'btn btn-danger',
      data: { confirm: "Do you want to delete this topic?" } %>
    </div>

  <% @topic.bookmarks.each do |bookmark, url| %>
  <div class="col-md-4">
    <div class="media">
      <div class="media-body">
        <%= link_to bookmark.url, topic_bookmark_path(@topic, bookmark), class: 'embedly-card' %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <h2>My RockMarks</h2>
    <div class="col-md-4">
      <% @user_bookmarks.each do |bookmark| %>
        <%= "##{bookmark.topic.title}" %>
        <br>
        <%= link_to bookmark.url, topic_bookmark_path(bookmark.topic, bookmark) %> <%= link_to "Delete Bookmark", [@topic, bookmark], method: :delete, class: 'btn btn-danger'%>
        <br>
      <% end %>
    </div>
  </div>
</div>
  <br />
<div class="container">
  <div class="row">
    <h2>Liked RockMarks</h2>
    <div class="col-md-4">
      <% @liked_bookmarks.each do |bookmark| %>
        <%= "##{bookmark.topic.title}" %>
        <br>
        <%= link_to bookmark.url, topic_bookmark_path(bookmark.topic, bookmark) %> <%= render partial: 'likes/like', locals: { bookmark: bookmark } %>
        <br>
      <% end %>
    </div>
  </div>
</div>

app/views/welcome/about.html.erb
<div class="container">
  <h1>About</h1>
    <ul>
      <li>Rockmarks</li>
      <li>Create a Topic</li>
      <li>Match it with a bookmark</li>
    </ul>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1 class="center">Rockmarks</h1>
  <p class="center">Rock The Marks with Bookmarks!</p>
  <p class="center"> Please <%= link_to "Register", new_user_registration_path, class: 'btn btn-primary' %> with us or <%= link_to "Log In", new_user_session_path, class: 'btn btn-primary' %></p>
</div>

<div class="header">
  <div class="col-lg-12">
    <div class="container">
      <div class="col-md-4">
        <h4>Best code school out there</h4>
        <a class="embedly-card" href="http://www.bloc.io">Bloc | Online Coding Bootcamp for Developers and Web Designers</a>
        <script async src="//cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>
      </div>
      <div class="col-md-4">
        <h4>Need help with code?</h4>
          <a class="embedly-card" href="http://www.stackoverflow.com">Stack Overflow</a>
          <script async src="//cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>
      </div>
    </div>
  </div>
</div>